# GitHub Sponsors & Funding
# These links appear on the "Sponsor" button in the repository

github: [Afrasyaab-GH, alhaq-studio, alhaq-initiative]
patreon: alhaq
buy_me_a_coffee: alhaq
ko_fi: alhaq

custom: ['https://alhaq.uk', 'https://alhaq-initiative.org']
